[tool.poetry]
name = "yomitoku-test"
version = "0.1.0"
description = ""
authors = ["tacogips <me@tacogips.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
yomitoku = "^0.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
